name: 'Version Publisher'
description: 'Automated version tagging and workflow triggering'
author: 'CYP'
inputs:
  version-data:
    description: 'JSON version data (must contain version fields)'
    required: true
  GITEA_TOKEN:
    description: 'Token for Gitea API access'
    required: true
  GITEA_SERVER:
    description: 'Gitea server URL'
    required: true
  workflow-file:
    description: 'Target workflow filename'
    required: true
    default: '📦amd64版本发布.yaml'
runs:
  using: 'node20'
  main: 'dist/index.js'